### ISSUE TITLE
Add dictionary of person names and rely on it

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/person-name-annotator-example#11]
- [x] Person last name
- [x] Person firstname

**Comment by gkowalski** [comment]
Modify the current process to rely on a fixed list of random PERSON names , for this example,  and remove the actual NLP processing.

**Comment by tschaffter** [comment]
I achieved this by taking the list of 1000 most popular last names from census.gov. We should extend this approach for firstnames.

**Comment by tschaffter** [comment]
Done in 39de11ff433ccfef946fe2605188d3604c4f26b5
